[package]
name = "copy-translator"
version = "0.3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = "s"
codegen-units = 1

[dependencies]
clipboard = "0.5"
cfg-if = "1"
config = "0.13"
deepl = { package = "deepl-api-client", version = "0.2" }
eframe = "0.18"
egui = "0.18"
egui_glium = "0.18"
enigo = "0"
glium = "0.31"
lazy_static = "1.4"
log = "0.4"
piet-common = "0.5"
tauri-hotkey = "0.1"
copypasta = "0.8"
ico = "0.1"
rdev = "0.5"
poll-promise = "0.1"

[build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "copy-translator.exe"
LegalCopyright = "Copyright © 2021-2022 zu1k"
ProductName = "CopyTranslator"
ProductVersion = "0.3.0"
FileDescription = "CopyTranslator: 简单、轻量、好用的划词翻译软件，利用DeepL翻译"
